/**
 * @file    timebase.h
 * @brief   Horizontal timebase table: time/div -> TIM6 divider, ADC sampling
 *          time and record length. The table itself is generated by
 *          tools/gen_timebase.py so the derivation is reproducible.
 */
#ifndef TIMEBASE_H
#define TIMEBASE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** ADC sampling time, portable encoding (mapped to HAL constants in acq_hw.c). */
typedef enum {
    SMP_2C5 = 0, SMP_6C5, SMP_12C5, SMP_24C5,
    SMP_47C5, SMP_92C5, SMP_247C5, SMP_640C5,
    SMP_COUNT
} adc_smp_t;

typedef struct {
    uint32_t ns_per_div;  /**< displayed time per horizontal division        */
    uint16_t psc;         /**< TIM6 prescaler                                 */
    uint16_t arr;         /**< TIM6 auto-reload                               */
    uint8_t  smp;         /**< adc_smp_t                                      */
    uint16_t record_len;  /**< samples per record (= samples on screen)       */
} timebase_t;

extern const timebase_t g_timebases[];
extern const uint8_t    g_timebase_count;

#define TIMEBASE_DEFAULT_INDEX  4u   /* 100 us/div */

/** Timer clock cycles between two ADC triggers. */
static inline uint32_t tb_period_cycles(const timebase_t *tb)
{
    return ((uint32_t)tb->psc + 1u) * ((uint32_t)tb->arr + 1u);
}

/** Exact sample rate in Hz (clock / integer divider). */
float tb_sample_rate_hz(const timebase_t *tb);

/** Sampling time in ADC cycles x2 (e.g. 2.5 cycles -> 5). */
uint32_t tb_smp_cycles_x2(adc_smp_t smp);

/** True if the entry is physically realizable (ADC fast enough, fits buffer). */
bool tb_is_valid(const timebase_t *tb);

/** Format ns/div as a short label: "5us", "200us", "1ms", "500ms". */
size_t tb_format_div(char *dst, size_t cap, uint32_t ns_per_div);

#ifdef __cplusplus
}
#endif
#endif /* TIMEBASE_H */
