/* AUTO-GENERATED by tools/gen_timebase.py - do not edit by hand. */
#include "timebase.h"

const timebase_t g_timebases[] = {
    /* ns/div        PSC   ARR  SMP  record     Fs */
    {        5000u,    0u,    15u, 0u,   200u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {       10000u,    0u,    15u, 0u,   400u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {       20000u,    0u,    15u, 0u,   800u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {       50000u,    0u,    15u, 0u,  2000u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {      100000u,    0u,    15u, 0u,  4000u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {      200000u,    0u,    15u, 0u,  8000u }, /*    5.0000 MS/s, sampling 2.5 cyc */
    {      500000u,    0u,    20u, 1u, 15238u }, /*    3.8095 MS/s, sampling 6.5 cyc */
    {     1000000u,    0u,    41u, 3u, 15238u }, /*    1.9048 MS/s, sampling 24.5 cyc */
    {     2000000u,    0u,    83u, 4u, 15238u }, /*    0.9524 MS/s, sampling 47.5 cyc */
    {     5000000u,    0u,   208u, 5u, 15311u }, /*    0.3828 MS/s, sampling 92.5 cyc */
    {    10000000u,    0u,   416u, 6u, 15347u }, /*    0.1918 MS/s, sampling 247.5 cyc */
    {    20000000u,    0u,   833u, 7u, 15347u }, /*    0.0959 MS/s, sampling 640.5 cyc */
    {    50000000u,    0u,  2083u, 7u, 15355u }, /*    0.0384 MS/s, sampling 640.5 cyc */
    {   100000000u,    0u,  4166u, 7u, 15358u }, /*    0.0192 MS/s, sampling 640.5 cyc */
    {   200000000u,    0u,  8333u, 7u, 15358u }, /*    0.0096 MS/s, sampling 640.5 cyc */
    {   500000000u,    0u, 20833u, 7u, 15359u }, /*    0.0038 MS/s, sampling 640.5 cyc */
};

const uint8_t g_timebase_count = (uint8_t)(sizeof g_timebases / sizeof g_timebases[0]);
