#!/usr/bin/env python3
"""Generate Core/App/timebase_table.c.

For each display time/div the script picks the *fastest* sample clock that
  1. is an integer division D of the 80 MHz timer clock (TIM6: D=(PSC+1)(ARR+1)),
  2. is not faster than the ADC can convert (D >= MIN_D ADC cycles), and
  3. keeps the whole on-screen window (8 divisions) inside ACQ_RECORD_MAX
     samples of the circular buffer,
then chooses the *longest* ADC sampling time that still fits in D cycles
(longer sampling = lower source-impedance sensitivity, better accuracy).

Nothing here is a measured number: sample rates are exact by construction
(clock / integer), accuracy of the clock itself is a validation item.
"""
import math
import pathlib

TIMER_CLK = 80_000_000
RECORD_MAX = 16384 - 1024
HDIVS = 8
# 2.5 + 12.5 = 15 cycles (5.333 MS/s) is the datasheet limit. The table stops
# one cycle short of it (5.000 MS/s) to keep margin until the limit has been
# characterized on hardware; set MIN_D = 15 to try the absolute maximum.
MIN_D = 16
SMP = [2.5, 6.5, 12.5, 24.5, 47.5, 92.5, 247.5, 640.5]
NS_PER_DIV = [5_000, 10_000, 20_000, 50_000, 100_000, 200_000, 500_000,
              1_000_000, 2_000_000, 5_000_000, 10_000_000, 20_000_000,
              50_000_000, 100_000_000, 200_000_000, 500_000_000]


def split(d):
    """Return (psc, arr) with (psc+1)*(arr+1) == d, preferring psc = 0."""
    for psc in range(0, 65536):
        if d % (psc + 1) == 0 and d // (psc + 1) <= 65536:
            return psc, d // (psc + 1) - 1
    raise ValueError(d)


rows = []
for ns in NS_PER_DIV:
    window_cycles = ns * HDIVS * TIMER_CLK // 1_000_000_000
    d = max(MIN_D, math.ceil(window_cycles / RECORD_MAX))
    rec = window_cycles // d
    assert 192 <= rec <= RECORD_MAX, (ns, d, rec)
    smp = max(i for i, s in enumerate(SMP) if s + 12.5 <= d)
    psc, arr = split(d)
    rows.append((ns, psc, arr, smp, rec, TIMER_CLK / d))

out = ["/* AUTO-GENERATED by tools/gen_timebase.py - do not edit by hand. */",
       '#include "timebase.h"', "",
       "const timebase_t g_timebases[] = {",
       "    /* ns/div        PSC   ARR  SMP  record     Fs */"]
for ns, psc, arr, smp, rec, fs in rows:
    out.append(f"    {{ {ns:>11}u, {psc:>4}u, {arr:>5}u, {smp}u, {rec:>5}u }}, "
               f"/* {fs/1e6:9.4f} MS/s, sampling {SMP[smp]} cyc */")
out += ["};", "",
        "const uint8_t g_timebase_count = (uint8_t)(sizeof g_timebases / sizeof g_timebases[0]);",
        ""]
dst = pathlib.Path(__file__).resolve().parents[1] / "Core/App/timebase_table.c"
dst.write_text("\n".join(out))
print("\n".join(out))
